### ISSUE TITLE
Running with Scipy version 1.130 gives an error

### ISSUE THREAD

**Issue by chetankumar** [urchade/GLiNER#62] opened 2024-04-11 10:42 UTC
# Code:
`from gliner import GLiNER

#Initialize GLiNER with the base model
model = GLiNER.from_pretrained("urchade/gliner_medium-v2.1")`

# Error Summary
`---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[2], [line 1](vscode-notebook-cell:?execution_count=2&line=1)
----> [1](vscode-notebook-cell:?execution_count=2&line=1) from gliner import GLiNER
      [3](vscode-notebook-cell:?execution_count=2&line=3) # Initialize GLiNER with the base model
      [4](vscode-notebook-cell:?execution_count=2&line=4) model = GLiNER.from_pretrained("urchade/gliner_medium-v2.1")

File [c:\Users\cheta\.conda\envs\langchain\Lib\site-packages\gliner\__init__.py:3](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/gliner/__init__.py:3)
      [1](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/gliner/__init__.py:1) __version__ = "0.1.7"
----> [3](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/gliner/__init__.py:3) from .model import GLiNER
      [5](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/gliner/__init__.py:5) __all__ = ["GLiNER"]

File [c:\Users\cheta\.conda\envs\langchain\Lib\site-packages\gliner\model.py:13](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/gliner/model.py:13)
     [11](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/gliner/model.py:11) from gliner.modules.evaluator import Evaluator, greedy_search
     [12](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/gliner/model.py:12) from gliner.modules.span_rep import SpanRepLayer
---> [13](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/gliner/model.py:13) from gliner.modules.token_rep import TokenRepLayer
     [14](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/gliner/model.py:14) from gliner.modules.token_splitter import WhitespaceTokenSplitter, MecabKoTokenSplitter
     [15](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/gliner/model.py:15) from torch import nn

File [c:\Users\cheta\.conda\envs\langchain\Lib\site-packages\gliner\modules\token_rep.py:5](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/gliner/modules/token_rep.py:5)
      [3](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/gliner/modules/token_rep.py:3) import torch
      [4](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/gliner/modules/token_rep.py:4) from flair.data import Sentence
----> [5](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/gliner/modules/token_rep.py:5) from flair.embeddings import TransformerWordEmbeddings
      [6](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/gliner/modules/token_rep.py:6) from torch import nn
      [7](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/gliner/modules/token_rep.py:7) from torch.nn.utils.rnn import pad_sequence

File [c:\Users\cheta\.conda\envs\langchain\Lib\site-packages\flair\__init__.py:42](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/flair/__init__.py:42)
     [39](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/flair/__init__.py:39) # global variable: arrow symbol
     [40](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/flair/__init__.py:40) _arrow = " → "
---> [42](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/flair/__init__.py:42) from . import (  # noqa: E402 import after setting device
     [43](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/flair/__init__.py:43)     data,
     [44](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/flair/__init__.py:44)     models,
     [45](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/flair/__init__.py:45)     nn,
     [46](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/flair/__init__.py:46)     trainers,
     [47](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/flair/__init__.py:47)     visual,
     [48](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/flair/__init__.py:48) )
     [50](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/flair/__init__.py:50) logging.config.dictConfig(
     [51](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/flair/__init__.py:51)     {
     [52](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/flair/__init__.py:52)         "version": 1,
   (...)
     [64](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/flair/__init__.py:64)     }
     [65](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/flair/__init__.py:65) )
     [67](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/flair/__init__.py:67) logger = logging.getLogger("flair")

File [c:\Users\cheta\.conda\envs\langchain\Lib\site-packages\flair\models\__init__.py:1](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/flair/models/__init__.py:1)
----> [1](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/flair/models/__init__.py:1) from .clustering import ClusteringModel
      [2](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/flair/models/__init__.py:2) from .entity_linker_model import SpanClassifier
      [3](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/flair/models/__init__.py:3) from .language_model import LanguageModel

File [c:\Users\cheta\.conda\envs\langchain\Lib\site-packages\flair\models\clustering.py:14](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/flair/models/clustering.py:14)
     [12](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/flair/models/clustering.py:12) from flair.data import Corpus, _iter_dataset
     [13](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/flair/models/clustering.py:13) from flair.datasets import DataLoader
---> [14](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/flair/models/clustering.py:14) from flair.embeddings import DocumentEmbeddings
     [16](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/flair/models/clustering.py:16) log = logging.getLogger("flair")
     [19](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/flair/models/clustering.py:19) class ClusteringModel:

File [c:\Users\cheta\.conda\envs\langchain\Lib\site-packages\flair\embeddings\__init__.py:13](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/flair/embeddings/__init__.py:13)
     [10](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/flair/embeddings/__init__.py:10) from .base import Embeddings, ScalarMix
     [12](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/flair/embeddings/__init__.py:12) # Expose document embedding classes
---> [13](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/flair/embeddings/__init__.py:13) from .document import (
     [14](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/flair/embeddings/__init__.py:14)     DocumentCNNEmbeddings,
     [15](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/flair/embeddings/__init__.py:15)     DocumentEmbeddings,
     [16](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/flair/embeddings/__init__.py:16)     DocumentLMEmbeddings,
     [17](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/flair/embeddings/__init__.py:17)     DocumentPoolEmbeddings,
     [18](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/flair/embeddings/__init__.py:18)     DocumentRNNEmbeddings,
     [19](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/flair/embeddings/__init__.py:19)     DocumentTFIDFEmbeddings,
     [20](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/flair/embeddings/__init__.py:20)     SentenceTransformerDocumentEmbeddings,
     [21](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/flair/embeddings/__init__.py:21)     TransformerDocumentEmbeddings,
     [22](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/flair/embeddings/__init__.py:22) )
     [24](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/flair/embeddings/__init__.py:24) # Expose image embedding classes
     [25](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/flair/embeddings/__init__.py:25) from .image import (
     [26](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/flair/embeddings/__init__.py:26)     ConvTransformNetworkImageEmbeddings,
     [27](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/flair/embeddings/__init__.py:27)     IdentityImageEmbeddings,
   (...)
     [30](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/flair/embeddings/__init__.py:30)     PrecomputedImageEmbeddings,
     [31](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/flair/embeddings/__init__.py:31) )

File [c:\Users\cheta\.conda\envs\langchain\Lib\site-packages\flair\embeddings\document.py:16](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/flair/embeddings/document.py:16)
     [10](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/flair/embeddings/document.py:10) from flair.data import Sentence
     [11](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/flair/embeddings/document.py:11) from flair.embeddings.base import (
     [12](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/flair/embeddings/document.py:12)     DocumentEmbeddings,
     [13](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/flair/embeddings/document.py:13)     load_embeddings,
     [14](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/flair/embeddings/document.py:14)     register_embeddings,
     [15](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/flair/embeddings/document.py:15) )
---> [16](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/flair/embeddings/document.py:16) from flair.embeddings.token import FlairEmbeddings, StackedEmbeddings, TokenEmbeddings
     [17](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/flair/embeddings/document.py:17) from flair.embeddings.transformer import (
     [18](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/flair/embeddings/document.py:18)     TransformerEmbeddings,
     [19](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/flair/embeddings/document.py:19)     TransformerOnnxDocumentEmbeddings,
     [20](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/flair/embeddings/document.py:20) )
     [21](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/flair/embeddings/document.py:21) from flair.nn import LockedDropout, WordDropout

File [c:\Users\cheta\.conda\envs\langchain\Lib\site-packages\flair\embeddings\token.py:10](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/flair/embeddings/token.py:10)
      [7](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/flair/embeddings/token.py:7) from pathlib import Path
      [8](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/flair/embeddings/token.py:8) from typing import Any, Dict, List, Optional, Union
---> [10](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/flair/embeddings/token.py:10) import gensim
     [11](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/flair/embeddings/token.py:11) import numpy as np
     [12](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/flair/embeddings/token.py:12) import torch

File [c:\Users\cheta\.conda\envs\langchain\Lib\site-packages\gensim\__init__.py:11](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/gensim/__init__.py:11)
      [7](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/gensim/__init__.py:7) __version__ = '4.3.2'
      [9](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/gensim/__init__.py:9) import logging
---> [11](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/gensim/__init__.py:11) from gensim import parsing, corpora, matutils, interfaces, models, similarities, utils  # noqa:F401
     [14](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/gensim/__init__.py:14) logger = logging.getLogger('gensim')
     [15](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/gensim/__init__.py:15) if not logger.handlers:  # To ensure reload() doesn't add another one

File [c:\Users\cheta\.conda\envs\langchain\Lib\site-packages\gensim\corpora\__init__.py:6](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/gensim/corpora/__init__.py:6)
      [1](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/gensim/corpora/__init__.py:1) """
      [2](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/gensim/corpora/__init__.py:2) This package contains implementations of various streaming corpus I/O format.
      [3](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/gensim/corpora/__init__.py:3) """
      [5](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/gensim/corpora/__init__.py:5) # bring corpus classes directly into package namespace, to save some typing
----> [6](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/gensim/corpora/__init__.py:6) from .indexedcorpus import IndexedCorpus  # noqa:F401 must appear before the other classes
      [8](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/gensim/corpora/__init__.py:8) from .mmcorpus import MmCorpus  # noqa:F401
      [9](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/gensim/corpora/__init__.py:9) from .bleicorpus import BleiCorpus  # noqa:F401

File [c:\Users\cheta\.conda\envs\langchain\Lib\site-packages\gensim\corpora\indexedcorpus.py:14](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/gensim/corpora/indexedcorpus.py:14)
     [10](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/gensim/corpora/indexedcorpus.py:10) import logging
     [12](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/gensim/corpora/indexedcorpus.py:12) import numpy
---> [14](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/gensim/corpora/indexedcorpus.py:14) from gensim import interfaces, utils
     [16](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/gensim/corpora/indexedcorpus.py:16) logger = logging.getLogger(__name__)
     [19](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/gensim/corpora/indexedcorpus.py:19) class IndexedCorpus(interfaces.CorpusABC):

File [c:\Users\cheta\.conda\envs\langchain\Lib\site-packages\gensim\interfaces.py:19](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/gensim/interfaces.py:19)
      [7](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/gensim/interfaces.py:7) """Basic interfaces used across the whole Gensim package.
      [8](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/gensim/interfaces.py:8) 
      [9](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/gensim/interfaces.py:9) These interfaces are used for building corpora, model transformation and similarity queries.
   (...)
     [14](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/gensim/interfaces.py:14) 
     [15](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/gensim/interfaces.py:15) """
     [17](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/gensim/interfaces.py:17) import logging
---> [19](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/gensim/interfaces.py:19) from gensim import utils, matutils
     [22](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/gensim/interfaces.py:22) logger = logging.getLogger(__name__)
     [25](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/gensim/interfaces.py:25) class CorpusABC(utils.SaveLoad):

File [c:\Users\cheta\.conda\envs\langchain\Lib\site-packages\gensim\matutils.py:20](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/gensim/matutils.py:20)
     [18](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/gensim/matutils.py:18) import scipy.sparse
     [19](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/gensim/matutils.py:19) from scipy.stats import entropy
---> [20](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/gensim/matutils.py:20) from scipy.linalg import get_blas_funcs, triu
     [21](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/gensim/matutils.py:21) from scipy.linalg.lapack import get_lapack_funcs
     [22](file:///C:/Users/cheta/.conda/envs/langchain/Lib/site-packages/gensim/matutils.py:22) from scipy.special import psi  # gamma function utils

ImportError: cannot import name 'triu' from 'scipy.linalg' (c:\Users\cheta\.conda\envs\langchain\Lib\site-packages\scipy\linalg\__init__.py)`

# Resolution
The triu package from spicy has been deprecated and is not used in 1.13 (latest). 
Downgrading to spicy 1.12 resolved the issue.

**Comment by tomaarsen** [comment] 2024-04-15 17:52
I can reproduce this as well, thanks for mentioning the resolution, it prevented the bug in my demo: https://huggingface.co/spaces/tomaarsen/gliner_medium-v2.1

Solving the real problem at hand is tricky, because it originates through `gensim` which is required by `flair`.

**Comment by urchade** [comment] 2024-04-22 18:40
fixed in v0.1.8

**Closed by urchade** 2024-04-22 18:40 UTC
